spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  mail:
    host: smtp.gmail.com
    username: jira4jr@gmail.com
    password: ${MAIL_PASSWORD}
    port: 587

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}
server:
  port: ${SERVER_PORT:8080}